### ISSUE TITLE
feat(Builders): Respect Semantic-release NPM Plugin publishConfig options

### ISSUE THREAD

**Issue by andrew-welker** [ng-easy/platform#229] opened 2021-09-14 17:42 UTC
I've got a monorepo with libraries that I want to publish to a private registry instead of NPM. From looking at the code (unless I missed it), the builder doesn't look for the `publishConfig` option, which is what is used in the NPM Plugin to determine where to publish the NPM package. I'm using a config value as below for some other packages that aren't using NX and the monorepo configuration.

```json
"publishConfig": {
    "access": "restricted",
    "registry": "https://npm.pkg.github.com"
  },
```

**Comment by samuelfernandez** [comment] 2021-09-14 18:12
Hey! Thanks for filing the issue and the feedback. The builder uses semantic-release/npm internally to publish to npm. According to their docs it should automatically use the publishConfig if defined in your package.json, as explained here https://github.com/semantic-release/npm#npm-configuration

I wouldn't expect that any configuration is needed through the builder to accomplish that. Would you mind checking those docs and try again if it works for you? It is possible that you need to set env variables for authentication, or tweak .npmrc 

I'll do some tests from my side to check it as well

**Comment by samuelfernandez** [comment] 2021-09-14 18:16
Here you have the source code that resolves the registry: https://github.com/semantic-release/npm/blob/b88fc0e09d998a82c2c70a434ea5729603fd432d/lib/get-registry.js#L5

Besides that, would you be able to provide a link to a repo, or the execution logs?

Thanks!

**Comment by samuelfernandez** [comment] 2021-09-20 12:32
I can confirm that following the docs mentioned above I've been able to successfully publish to GitHub Packages, you can check this repo https://github.com/ng-easy/workspace-release-test with a working example. Closing since this doesn't seem to be an issue. I hope you can get it working @andrew-welker!

**Closed by samuelfernandez** 2021-09-20 12:32 UTC

**Comment by andrew-welker** [comment] 2021-09-20 14:59
Thanks for the information. This is a case where I wasn't clear on what would happen with the original Semantic Release configuration based on the documentation for this package. My assumption (incorrect, and based on the language in the docs for this package that mentioned that it has an opinionated configuration), was that stuff like this was configured internally.
